/**
 * TEMPLATE CONFIGURATION
 * 
 * This is a template file showing all configuration options.
 * Copy sections to your actual config files as needed.
 * 
 * DO NOT edit this file directly - it's just a reference!
 */

// ========================================
// TEMPLATE FOR website.config.ts
// ========================================

export const websiteConfigTemplate = {
  couple: {
    bride: {
      name: 'Jane',                      // ← Your bride's first name
      fullName: 'Jane Marie Smith',      // ← Full legal name
      photo: '/images/couple/bride.jpg', // ← Path to bride's photo
    },
    groom: {
      name: 'John',                      // ← Your groom's first name
      fullName: 'John Michael Doe',      // ← Full legal name
      photo: '/images/couple/groom.jpg', // ← Path to groom's photo
    },
  },

  wedding: {
    // Wedding date and time (YYYY-MM-DDTHH:mm:ss format)
    date: '2025-06-15T16:00:00',        // ← Your wedding date
    
    venue: {
      name: 'Grand Ballroom Hotel',      // ← Venue name
      address: '123 Main Street, City, State 12345', // ← Full address
      coordinates: {
        lat: 40.7128,                    // ← Latitude (get from Google Maps)
        lng: -74.0060,                   // ← Longitude
      },
    },

    schedule: [
      {
        time: '3:00 PM',
        event: 'Guest Arrival & Cocktail Hour',
        description: 'Welcome drinks and appetizers',
      },
      {
        time: '4:00 PM',
        event: 'Wedding Ceremony',
        description: 'Exchange of vows',
      },
      // Add more events...
    ],
  },

  site: {
    title: 'Jane & John\'s Wedding',
    description: 'Join us in celebrating our special day',
    url: 'https://yourwedding.com',
    
    admin: {
      username: 'admin',                 // ← Change this!
      password: 'change-this-password',  // ← Change this!
    },
  },

  features: {
    countdown: true,
    gallery: true,
    timeline: true,
    rsvp: true,
    guestbook: true,
    dailyReveals: true,
    videoMessages: true,
    quiz: true,
    dreamsBoard: true,
    notifications: true,
  },

  theme: {
    colors: {
      primary: '#FF69B4',    // Hot pink
      secondary: '#FFB6C1',  // Light pink
      accent: '#C71585',     // Medium violet red
    },
    style: 'romantic',       // romantic, celestial, modern, classic
  },

  social: {
    instagram: '@yourwedding',
    facebook: 'yourwedding',
    twitter: '@yourwedding',
    hashtag: '#YourWedding2025',
  },

  contact: {
    email: 'contact@yourwedding.com',
    phone: '+1 (555) 123-4567',
  },
};

// ========================================
// TEMPLATE FOR content.config.ts
// ========================================

export const contentConfigTemplate = {
  hero: {
    title: 'We\'re Getting Married!',
    subtitle: 'Join us for the celebration of a lifetime',
    welcomeMessage: 'Welcome to our wedding website...',
  },

  timeline: [
    {
      id: '1',
      date: new Date('2020-01-15'),
      title: 'First Date',
      description: 'The story of our first date...',
      image: '/images/timeline/first-date.jpg',
      location: {
        name: 'Restaurant Name',
        coordinates: { lat: 0.0, lng: 0.0 },
      },
    },
    {
      id: '2',
      date: new Date('2021-06-20'),
      title: 'The Proposal',
      description: 'How we got engaged...',
      image: '/images/timeline/proposal.jpg',
      location: {
        name: 'Proposal Location',
        coordinates: { lat: 0.0, lng: 0.0 },
      },
    },
    {
      id: '3',
      date: new Date('2025-06-15'),
      title: 'Our Wedding Day',
      description: 'Our beautiful wedding day...',
      image: '/images/timeline/wedding.jpg',
      location: {
        name: 'Wedding Venue',
        coordinates: { lat: 0.0, lng: 0.0 },
      },
    },
  ],

  videoMessages: [
    {
      id: '1',
      name: 'Mom',
      relationship: 'Mother',
      thumbnail: '/images/messages/mom-thumbnail.jpg',
      videoUrl: '/videos/messages/mom-message.mp4',
      message: 'A special message from mom',
      isLocked: false,
    },
    // Add more video messages...
  ],

  gallery: {
    title: 'Our Gallery',
    subtitle: 'A collection of our favorite memories',
    categories: ['All', 'Couple', 'Family', 'Friends', 'Travel'],
    defaultCaption: 'Beautiful moment together',
  },

  rsvp: {
    title: 'Will You Join Us?',
    subtitle: 'Please let us know if you can attend',
    confirmationMessage: 'Thank you for your RSVP!',
  },

  guestbook: {
    title: 'Guest Book',
    subtitle: 'Leave us a message',
    placeholders: {
      name: 'Your Name',
      message: 'Your message...',
    },
    submitButton: 'Sign Guest Book',
    successMessage: 'Thank you for your lovely message!',
  },
};

// ========================================
// TEMPLATE FOR assets.config.ts
// ========================================

export const assetsConfigTemplate = {
  couple: {
    hero: '/images/couple/hero.jpg',
    bride: '/images/couple/bride.jpg',
    groom: '/images/couple/groom.jpg',
    together: '/images/couple/together.jpg',
  },

  timeline: {
    'first-date': '/images/timeline/first-date.jpg',
    'proposal': '/images/timeline/proposal.jpg',
    'engagement': '/images/timeline/engagement.jpg',
    'wedding': '/images/timeline/wedding.jpg',
  },

  gallery: {
    folder: '/images/gallery/',
    categories: {
      couple: '/images/gallery/couple/',
      family: '/images/gallery/family/',
      friends: '/images/gallery/friends/',
      travel: '/images/gallery/travel/',
    },
  },

  videoMessages: {
    videosFolder: '/videos/messages/',
    thumbnailsFolder: '/images/messages/',
    videos: {
      'mom': {
        video: '/videos/messages/mom.mp4',
        thumbnail: '/images/messages/mom-thumb.jpg',
      },
      'dad': {
        video: '/videos/messages/dad.mp4',
        thumbnail: '/images/messages/dad-thumb.jpg',
      },
    },
  },

  dailyReveals: {
    folder: '/images/daily-reveals/',
    images: {
      'day-01': '/images/daily-reveals/day-01.jpg',
      'day-02': '/images/daily-reveals/day-02.jpg',
      // Add all 30 days...
    },
  },

  audio: {
    songs: [
      '/audio/songs/our-song.mp3',
      '/audio/songs/ceremony.mp3',
    ],
    defaultVolume: 0.3,
  },
};

// ========================================
// QUICK START CHECKLIST
// ========================================

export const quickStartChecklist = `
WEDDING WEBSITE SETUP CHECKLIST
================================

□ 1. UPDATE BASIC INFO (website.config.ts)
   □ Bride's name and photo
   □ Groom's name and photo
   □ Wedding date (YYYY-MM-DDTHH:mm:ss)
   □ Venue name and address
   □ Venue coordinates (from Google Maps)
   □ Wedding schedule/timeline

□ 2. ADD YOUR STORY (content.config.ts)
   □ Write timeline event descriptions
   □ Add locations for each event
   □ Customize page text (hero, RSVP, etc.)
   □ Add video message details

□ 3. ORGANIZE PHOTOS
   □ Create folders in /public/images/
   □ Upload couple photos
   □ Upload timeline photos
   □ Upload gallery photos
   □ Create video thumbnails

□ 4. UPDATE PATHS (assets.config.ts)
   □ Set couple photo paths
   □ Set timeline image paths
   □ Configure gallery folders
   □ Set video message paths

□ 5. OPTIONAL FEATURES
   □ Customize quiz (quiz.config.ts)
   □ Set up daily reveals (daily-reveals.config.ts)
   □ Choose theme colors
   □ Enable/disable features

□ 6. SECURITY & FINAL TOUCHES
   □ Change admin username
   □ Change admin password
   □ Update contact info
   □ Add social media links
   □ Proofread all text

□ 7. TESTING
   □ Run: npm run dev
   □ Test on mobile phone
   □ Test all links
   □ Test RSVP form
   □ Test video playback
   □ Check image loading

□ 8. DEPLOYMENT
   □ Build: npm run build
   □ Deploy to hosting
   □ Test production site
   □ Share with guests!

CONGRATULATIONS! 🎉
Your wedding website is ready!
`;

// ========================================
// EXAMPLE CONFIGURATIONS
// ========================================

export const examples = {
  // Example 1: Romantic Garden Wedding
  romanticGarden: {
    theme: {
      colors: {
        primary: '#FF69B4',
        secondary: '#FFB6C1',
        accent: '#FF1493',
      },
      style: 'romantic',
    },
    venue: {
      name: 'Rose Garden Estate',
      description: 'Outdoor garden ceremony',
    },
  },

  // Example 2: Modern City Wedding
  modernCity: {
    theme: {
      colors: {
        primary: '#2C3E50',
        secondary: '#ECF0F1',
        accent: '#3498DB',
      },
      style: 'modern',
    },
    venue: {
      name: 'Downtown Loft',
      description: 'Contemporary urban venue',
    },
  },

  // Example 3: Beach Destination Wedding
  beachDestination: {
    theme: {
      colors: {
        primary: '#00BCD4',
        secondary: '#B2EBF2',
        accent: '#FF9800',
      },
      style: 'celestial',
    },
    venue: {
      name: 'Sunset Beach Resort',
      description: 'Beachside ceremony at sunset',
    },
  },

  // Example 4: Classic Ballroom Wedding
  classicBallroom: {
    theme: {
      colors: {
        primary: '#8B4513',
        secondary: '#D4AF37',
        accent: '#FFD700',
      },
      style: 'classic',
    },
    venue: {
      name: 'Grand Ballroom Hotel',
      description: 'Traditional elegant ceremony',
    },
  },
};

